In [1]:
import pandas as pd
from pprint import pprint

In [10]:
df_rephrased = pd.read_csv("datasets/knowledge_non_knowledge_v3_evaluation_rogue_filtered_both_models_with_knowledge_neutral_oversampled.csv")

In [11]:
df_rephrased.head()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Repo,GitHub_Type,Nr,original_statement,rephrased_statement,Non_Knowledge_label_FSE_paper_Giuliano,...,original_Sol_Comments,original_Non_Knowledge_label_FSE_paper_Alena,original_Non_knowledge_label_Roberts_Alena,original_Alena_Comments,original_Roberts_label,original_FSE_label,original_binary_NK_label,original_final_label,original_rephrased_statement,final_label
0,1589,1589,1589,1647,pytorch_pytorch,pull,155734.0,torch.export.export() uses fake tensors during...,"When using torch.export.export(), fake tensors...",Knowledge,...,NaN,NaN,NaN,NaN,0,0,0,0.0,torch.export.export() uses fake tensors during...,0
1,1590,1590,1590,1648,pytorch_pytorch,pull,155734.0,torch.export.export() uses fake tensors during...,The issue arises because torch.export.export()...,Knowledge,...,NaN,NaN,NaN,NaN,0,0,0,0.0,torch.export.export() uses fake tensors during...,0
2,1591,1591,1591,1650,pytorch_pytorch,pull,155734.0,torch.export.export() uses fake tensors during...,"During export tracing, fake tensors don’t have...",Knowledge,...,NaN,NaN,NaN,NaN,0,0,0,0.0,torch.export.export() uses fake tensors during...,0
3,1592,1592,1592,1652,pytorch_pytorch,pull,155734.0,torch.export.export() uses fake tensors during...,The torch.export.export() system relies on fak...,Knowledge,...,NaN,NaN,NaN,NaN,0,0,0,0.0,torch.export.export() uses fake tensors during...,0
4,1593,1593,1593,1653,pytorch_pytorch,pull,155734.0,torch.export.export() uses fake tensors during...,When using torch.export.export() with RNN modu...,Knowledge,...,NaN,NaN,NaN,NaN,0,0,0,0.0,torch.export.export() uses fake tensors during...,0

In [12]:
ground_truth_in_training_stats = df_rephrased.groupby(by="original_statement").agg(count=("rephrased_statement", "count"))

ground_truth_in_training_stats.describe()

            count
count   18.000000
mean   177.000000
std     15.605429
min    143.000000
25%    167.500000
50%    179.000000
75%    189.500000
max    197.000000

In [8]:
df_rephrased_grouped = df_rephrased.groupby(by="Nr", group_keys=True)[["original_statement", "rephrased_statement"]].apply(lambda x:x)

In [9]:
df_rephrased_grouped.head()

                                          original_statement  \
Nr
17501 182  After testing on GPU, if I set the batch size ...
      183  After testing on GPU, if I set the batch size ...
      184  After testing on GPU, if I set the batch size ...
      185  After testing on GPU, if I set the batch size ...
      186  After testing on GPU, if I set the batch size ...

                                         rephrased_statement
Nr
17501 182  I've noticed that my model runs very efficient...
      183  When I run my model on the GPU, it performs we...
      184  I'm experiencing memory issues on my 8GB GPU w...
      185  My model runs quickly on the GPU with a batch ...
      186  I've observed that my model runs efficiently o...

In [34]:
row = 260

print("+++ ORIGINAL STATEMENT +++")
print(df_rephrased.iloc[row]["original_statement"])
print()
print("+++ REPHRASED STATEMENT +++")
print(df_rephrased.iloc[row]["rephrased_statement"])

+++ ORIGINAL STATEMENT +++
torch.export.export seems to produce invalid code for Tensor.split when used with meta device.

I am not sure if this is something that needs to be fixed, but here is the report anyway.

+++ REPHRASED STATEMENT +++
I found that torch.export.export generates invalid code when Tensor.split is used with the meta device. I'm not sure if this is a bug or if there's a specific reason for this, but I wanted to bring it to your attention.